ALTER TABLE Book
ADD GenreID NUMBER
ADD CONSTRAINT fk_genre
FOREIGN KEY (GenreID)
REFERENCES Genre (GenreID);

--RUN THIS CODE SEPERATERY
ALTER TABLE Book
ADD "OrderID" NUMBER
ADD CONSTRAINT fk_order_book
FOREIGN KEY ("OrderID")
REFERENCES "Order" ("OrderID");
